// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SET4dS9qV7ScIvyBXuzmhRMDw0LrsDk',
    appId: '1:574849261990:web:65e854f3cb74e0b5c4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    authDomain: 'naslookapp-ecf15.firebaseapp.com',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    measurementId: 'G-7ZMCBFELNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2slKpjtRNhbCHDWEO9G5s-z7J9ZG-I4M',
    appId: '1:574849261990:android:c979e5335381f7a6c4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAmReGVYYe7Hlk8NBzZtiqPDR3ABlso8',
    appId: '1:574849261990:ios:2a15ac0ec83da8d4c4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    iosBundleId: 'com.example.naslook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAmReGVYYe7Hlk8NBzZtiqPDR3ABlso8',
    appId: '1:574849261990:ios:2a15ac0ec83da8d4c4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    iosBundleId: 'com.example.naslook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SET4dS9qV7ScIvyBXuzmhRMDw0LrsDk',
    appId: '1:574849261990:web:59f16687dd56fd69c4af67',
    messagingSenderId: '574849261990',
    projectId: 'naslookapp-ecf15',
    authDomain: 'naslookapp-ecf15.firebaseapp.com',
    databaseURL: 'https://naslookapp-ecf15-default-rtdb.firebaseio.com',
    storageBucket: 'naslookapp-ecf15.firebasestorage.app',
    measurementId: 'G-409K5LVQM6',
  );
}
